### ISSUE TITLE
No database selected.

### ISSUE THREAD

**Issue by selonsy** [2881099/dotnetGen_mysql#1]
重现步骤：
1.下载示例程序，解压到指定文件夹。
2.打开MakeCode.exe。
3.录入参数：主机：127.0.0.1 用户：root 密码：**** 其余空。
4.点击Connect，报：No database selected 的错误。
5.过一会儿弹出警告窗口，提示：“您当前使用的版本未能实现功能！”
6.关掉两个弹出的窗口，报：Access Denied。

盼复。

**Comment by 2881099** [comment]
演示服手误更新错了文件导致的，源码没有问题
