### ISSUE TITLE
Error occurred while updating mysql

### ISSUE THREAD

**Issue by Baiqu** [2881099/dotnetGen_mysql#2]
Object reference not set to an instance of an object

Update
UpdateDiy

All update method will cause an error

**Comment by 2881099** [comment]
表结构方便发一份吗

**Comment by Baiqu** [comment]
你好！


insert 是OK，delete没有试过，
Test.Update
Test.UpdateDiy
都试过，全部提示有错误，看到日志中的SQL代码也是正确的。


这是表结构，谢谢！


CREATE TABLE `userother` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `userid` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `chinesename` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `englishname` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `doctype` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
  `idnumber` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
  `hasverify` bit(1) NOT NULL COMMENT '是否验证',
  `created` datetime NOT NULL,
  `images` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL ,
  PRIMARY KEY (`userid`),
  KEY `id` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci

 
 
------------------ Original ------------------

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/47888693-ccec0480-de80-11e8-8a43-89f57f599f7c.png)

已定位到原因，原因是10天前升级 SafeObjectPool，漏改了一个地方。然后这种好用的工具用户群体几乎没有，所以没人反馈。

待会发布 dng.Mysql 1.1.23 可以解决这个问题

**Comment by Baiqu** [comment]
嗯，非常认同，这是一个不错的工具，应该知道的人不多吧。


非常喜欢缓存壳，还有更新的设计，可以指定字段的更新。


谢谢，能及时升级解决问题！
 
 
------------------ Original ------------------
