### ISSUE TITLE
SqlHelper.cs 33行提示错误

### ISSUE THREAD

**Issue by Baiqu** [2881099/dotnetGen_mysql#3]
你好！

Instance = new Executer(cache, masterConnectionString, slaveConnectionString, log);

错误内容：
System.MissingMethodException:“Method not found: 'System.String[] CSRedis.CSRedisClient.HashMGet(System.String, System.String[])'.”

使用Rdis后，就会发生错误，如果不使用Rdis，就不会出错。
之前的版本好像，在Redis下没有这个错误。

**Comment by 2881099** [comment]
把 CSRedisCore，Caching.CSRedis 升级到最新

**Comment by 2881099** [comment]
原因是最新升级 csredis 造成的。方法名统与redis-cli统一了

**Comment by 2881099** [comment]
xxx.db.csproj
Infrastructure.csproj

这两个项目的引用

**Comment by Baiqu** [comment]
我把csrediscore 降级到2.6.12是可以正常的。新的是否暂时不要更新。

**Comment by 2881099** [comment]
升吧，没有事的，升完后重新生成一下 xxx.db 的代码

![image](https://user-images.githubusercontent.com/16286519/47898667-c32ec500-deb1-11e8-9439-cea72b464241.png)

如果有类似这个文件，双击过一会就自动生成完毕

**Comment by Baiqu** [comment]
好的，重新生成一个相关文件

**Comment by Baiqu** [comment]
这个生成工具， 好像不支持mysql 8.0  ，会提示无法读取表， 可能与8.0的安全机制有关， 
Retrieval of the RSA public key is not enabled for insecure connections.

   mysql 5.7 可以读取。

**Comment by 2881099** [comment]
5.7 以上的高级特性没支持，因为mysql分支版本太多

**Comment by Baiqu** [comment]
使用方面，应该没问题吧。 只是生成有些小麻烦，我另外导入到5.7中，生成文件。

**Comment by 2881099** [comment]
mysql 8.0 我大概知道是什么原因

你试试

Data Source={0};Port={1};User ID={2};Password={3};Initial Catalog={4};Charset=utf8

MySqlConnection 连接执行

select schema_name from information_schema.schemata where schema_name not in ('information_schema', 'mysql', 'performance_schema')

**Comment by 2881099** [comment]
然后以下的连接串也试试

Data Source={0};Port={1};User ID={2};Password={3};Initial Catalog={4};Charset=utf8;SslMode=none

**Comment by Baiqu** [comment]
使用方面可以，连接成功，增加SslMode 就可以了。  生成工具的命令行，不能修改连接字符串。

**Comment by 2881099** [comment]
你用的是 GenMy 命令吗？看看什么版本

**Comment by 2881099** [comment]
dotnet tool list -g

**Comment by Baiqu** [comment]
1.1.12 GenMy

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/47899621-0c344880-deb5-11e8-814c-e95d58c14f5f.png)

代码中写死了 SslMode=none，不加这个参数某些版本也会报错。

需要找两全其美的办法，你那边正确的连接串，完整的应该是怎样的？

**Comment by 2881099** [comment]
如果有必要，可以下载源码修改，发布一个你私人专属的客户端

源代码在：dotnetGen_mysql/GenMy/ConsoleApp.cs 527行，542行

**Comment by Baiqu** [comment]
嗯，那有些奇怪了。 8.0下，命令工具，显示无法读取表...
5.7可以正常用命令生成代码 。
客户端最终还是使用的 8.0, 同一个数据库帐户。 工具下不可以。

我再更新时，下载源代码，研究一下，是哪里出错。谢谢你！

**Comment by 2881099** [comment]
https://blog.csdn.net/Yuriey/article/details/80423504
关于JDBC连接数据库时出现的Public Key Retrieval is not allowed错误

以及下载 MySql.Data 源码，查看后确定基本是要传递 AllowPublicKeyRetrieval=true 参数，但需要确认老版本不会因为此参数影响连接。

dotnet tool update GenMs -g
更新到 1.1.13 试试连 mysql server 8.0，目前已确认连接 mysql server 5.6，mariadb 10 不会报错。

**Comment by Baiqu** [comment]
厉害，升级解决了，谢谢！

**Comment by Baiqu** [comment]
dotnet tool update GenMy -g
是mysql ，这个工具名称是GenMy
升级成功了。1.1.13了。
