### ISSUE TITLE
发现问题，生成代码会等待很久，之后显示失败

### ISSUE THREAD

**Issue by Baiqu** [2881099/dotnetGen_mysql#4]
Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.

查了源代码，这个功能实现，原来是通过218.6.8.9:29888，来完成的，请问这个能本地搭建吗？

**Comment by Baiqu** [comment]
<img width="540" alt="null" src="https://user-images.githubusercontent.com/5540970/48114155-e6ce8280-e298-11e8-91ad-500623fc8f71.PNG">

**Comment by 2881099** [comment]
可以搭建的，但是不能用 GenMy 了，需要重新编译一个版本。
见 GenMy/ConsoleApp.cs 172行，修改为你本地服务器ip:port

ServerWinForm/ServerWinSerice部署在本地，app.config 可以修改端口
ServerWinForm是窗口运行的。
ServerWinSerice需要安装windows服务。
都在 .net framework 2.0+ 上运行。

**Comment by 2881099** [comment]
生成器框架是client, server架构。

client 负责输入，以及 ado.net 执行得到数据库结构。
server 负责按结构生成代码。

这种架构的设计是为了热更新，server的生成代码规则和逻辑可以马上修改生效，不必更新客户端。

**Comment by Baiqu** [comment]
嗯，原来是这样设计的，这样确实也有很方便的地方，客户端可以不再更新，就能升级。
谢谢
